import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'docs-home',
    'getting-started',
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/overview-blackroad-os-overview',
        'overview/overview-stack-map',
        'overview/overview-seasons',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      items: [
        'services/services-service-api',
        'services/services-service-operator',
        'services/services-service-core',
        'services/services-service-web',
        'services/services-service-prism-console',
        'services/services-service-infra',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [
        'agents/agents-agent-ecosystem',
        'agents/agents-agent-identity-and-memory',
        'dev/dev-agents-atlas-and-friends',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/guides-getting-started-local',
        'guides/guides-contributing',
        'guides/guides-coding-standards',
      ],
    },
    {
      type: 'category',
      label: 'Runbooks',
      items: [
        'runbooks/runbooks-incident-playbook',
        'runbooks/runbooks-deploy-api',
        'runbooks/runbooks-deploy-operator',
        'runbooks/runbooks-deploy-web',
        'runbooks/runbooks-deploy-prism',
        'runbooks/runbooks-debug-operator',
        'runbooks/runbooks-rollback-procedures',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/reference-api-surface',
        'dev/dev-core-primitives',
        'dev/dev-api-overview',
        'dev/dev-events-and-roadchain',
      ],
    },
    {
      type: 'category',
      label: 'Operate the OS',
      items: [
        'ops/ops-prism-console',
        'ops/ops-operator-runtime',
        'ops/ops-infra-guide',
      ],
    },
    {
      type: 'category',
      label: 'Business & Vision',
      items: [
        'business/business-pain-points',
        'business/business-value-proposition',
      ],
    },
    {
      type: 'category',
      label: 'Meta',
      items: [
        'meta/meta-system-prompt',
        'meta/meta-style-guide',
        'meta/meta-docs-contributing',
        'meta/meta-docs-mega-prompt',
        'meta/meta-glossary',
        'meta/meta-master-codex-prompt',
        'meta/meta-architecture-decisions',
      ],
    },
    {
      type: 'category',
      label: 'System Prompts',
      items: [
        'system/prompts/system-docs-master-prompt',
      ],
    },
  ],
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
